config-version: 1
language: en
debug: false

storage:
  type: yaml

redis:
  enabled: false

discord:
  enabled: false

placeholderapi:
  enabled: true

skinsrestorer:
  enabled: true

metrics:
  enabled: true

update-checker:
  enabled: true

folia:
  compatibility-mode: auto

permissions:
  admin: announcer.admin
  receive-default: announcer.receive.alert

scheduler:
  enabled: true
  default-interval-seconds: 300

defaults:
  enabled: true
  priority: 0
  channels:
    - CHAT
