# @authors Lavender
# Rol de este servidor en tu red: AUTH | SPAWN | SURVIVAL
server-role: SPAWN

welcome:
  enabled: true
  first-join:
    chat: "&aBienvenido &e%player% &aa nuestra comunidad! &7(primera vez)"
    title:
      enabled: true
      main: "&a¡Bienvenido!"
      sub: "&fDisfruta tu estadía, %player%"
      fade-in: 10
      stay: 50
      fade-out: 10
    sound: "ENTITY_PLAYER_LEVELUP"
  rejoin:
    chat: "&a¡%player% ha entrado! &7Salúdenlo 👋"
    title:
      enabled: false
    sound: "UI_TOAST_CHALLENGE_COMPLETE"

donations:
  enabled: true
  format: "&6[Donación] &e%player% &fapoyó con &b%item% &f(&a%monto%&f) ¡Gracias!"
  sound: "ENTITY_VILLAGER_CELEBRATE"
  proxy-forward:
    enabled: false
    target-servers: ["spawn", "survival"]

messages:
  disabled-on-auth: "&7[WD] Este plugin está deshabilitado en servidores de AUTH."
  no-permission: "&cNo tienes permiso."
  usage-donate: "&eUso: /donatebroadcast <jugador> <paquete|motivo> [monto]"
