# @authors Lavender
name: WelcomeDonations
main: org.lavender.wd.WelcomeDonationsPlugin
version: 1.0.0
api-version: '1.21'
author: Lavender

commands:
  donatebroadcast:
    description: Anuncia una donación globalmente.
    usage: /donatebroadcast <jugador> <paquete|motivo> [monto]
    aliases: [donar, donateannounce]
    permission: wd.donate.broadcast

permissions:
  wd.admin:
    description: Acceso a todos los comandos de administración.
    default: op
  wd.donate.broadcast:
    description: Permite anunciar donaciones manualmente.
    default: op

softdepend: [Tebex, CraftingStore]
